=== robbyn/pureport/src/org/librebiz/pureport/reportfile/report.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT report (page-layout, (script|macro)*, before?, after?,
        report-header?, report-footer?, page-header?, page-footer?,
        (band|script|iterate|choose|call)*)>
<!ATTLIST report
    default-units (cm|mm|in|pt|pc|px) #IMPLIED
    script-engine CDATA #IMPLIED
>

<!ELEMENT page-layout EMPTY>
<!ATTLIST page-layout
    paper-width CDATA #IMPLIED
    paper-height CDATA #IMPLIED
    left-margin CDATA #IMPLIED
    top-margin CDATA #IMPLIED
    right-margin CDATA #IMPLIED
    bottom-margin CDATA #IMPLIED
    orientation (portrait|landscape|reverse-landscape) #IMPLIED
>

<!ELEMENT script (#PCDATA)>

<!ELEMENT macro (band|script|iterate|choose|call)*>
<!ATTLIST macro
    name CDATA #REQUIRED
    arguments CDATA #IMPLIED
>

<!ELEMENT condition (#PCDATA)>

<!ELEMENT before (#PCDATA)>

<!ELEMENT after (#PCDATA)>

<!ELEMENT report-header (condition?, before?, after?, row+, column+, cell*)>
<!ATTLIST report-header
    condition CDATA #IMPLIED
    top-margin CDATA #IMPLIED
    bottom-margin CDATA #IMPLIED
    left-margin CDATA #IMPLIED
    right-margin CDATA #IMPLIED
    top-padding CDATA #IMPLIED
    bottom-padding CDATA #IMPLIED
    left-padding CDATA #IMPLIED
    right-padding CDATA #IMPLIED
    background CDATA #IMPLIED
    vertical-align (top|bottom|center) #IMPLIED
    align (left|right|center|justify) #IMPLIED
    border CDATA #IMPLIED
    border-left CDATA #IMPLIED
    border-right CDATA #IMPLIED
    border-top CDATA #IMPLIED
    border-bottom CDATA #IMPLIED
>

<!ELEMENT report-footer (condition?, before?, after?, row+, column+, cell*)>
<!ATTLIST report-footer
    condition CDATA #IMPLIED
    top-margin CDATA #IMPLIED
    bottom-margin CDATA #IMPLIED
    left-margin CDATA #IMPLIED
    right-margin CDATA #IMPLIED
    top-padding CDATA #IMPLIED
    bottom-padding CDATA #IMPLIED
    left-padding CDATA #IMPLIED
    right-padding CDATA #IMPLIED
    background CDATA #IMPLIED
    vertical-align (top|bottom|center) #IMPLIED
    align (left|right|center|justify) #IMPLIED
    border CDATA #IMPLIED
    border-left CDATA #IMPLIED
    border-right CDATA #IMPLIED
    border-top CDATA #IMPLIED
    border-bottom CDATA #IMPLIED
>

<!ELEMENT page-header (condition?, before?, after?, row+, column+, cell*)>
<!ATTLIST page-header
    condition CDATA #IMPLIED
    top-margin CDATA #IMPLIED
    bottom-margin CDATA #IMPLIED
    left-margin CDATA #IMPLIED
    right-margin CDATA #IMPLIED
    top-padding CDATA #IMPLIED
    bottom-padding CDATA #IMPLIED
    left-padding CDATA #IMPLIED
    right-padding CDATA #IMPLIED
    background CDATA #IMPLIED
    vertical-align (top|bottom|center) #IMPLIED
    align (left|right|center|justify) #IMPLIED
    border CDATA #IMPLIED
    border-left CDATA #IMPLIED
    border-right CDATA #IMPLIED
    border-top CDATA #IMPLIED
    border-bottom CDATA #IMPLIED
>

<!ELEMENT page-footer (condition?, before?, after?, row+, column+, cell*)>
<!ATTLIST page-footer
    condition CDATA #IMPLIED
    top-margin CDATA #IMPLIED
    bottom-margin CDATA #IMPLIED
    left-margin CDATA #IMPLIED
    right-margin CDATA #IMPLIED
    top-padding CDATA #IMPLIED
    bottom-padding CDATA #IMPLIED
    left-padding CDATA #IMPLIED
    right-padding CDATA #IMPLIED
    background CDATA #IMPLIED
    vertical-align (top|bottom|center) #IMPLIED
    align (left|right|center|justify) #IMPLIED
    border CDATA #IMPLIED
    border-left CDATA #IMPLIED
    border-right CDATA #IMPLIED
    border-top CDATA #IMPLIED
    border-bottom CDATA #IMPLIED
>

<!ELEMENT band (condition?, before?, after?, row+, column+, cell*)>
<!ATTLIST band
    condition CDATA #IMPLIED
    top-margin CDATA #IMPLIED
    bottom-margin CDATA #IMPLIED
    left-margin CDATA #IMPLIED
    right-margin CDATA #IMPLIED
    top-padding CDATA #IMPLIED
    bottom-padding CDATA #IMPLIED
    left-padding CDATA #IMPLIED
    right-padding CDATA #IMPLIED
    background CDATA #IMPLIED
    vertical-align (top|bottom|center) #IMPLIED
    align (left|right|center|justify) #IMPLIED
    border CDATA #IMPLIED
    border-left CDATA #IMPLIED
    border-right CDATA #IMPLIED
    border-top CDATA #IMPLIED
    border-bottom CDATA #IMPLIED
>

<!ELEMENT iterate (band|script|iterate|choose|call)*>
<!ATTLIST iterate
    id CDATA #REQUIRED
    index-id CDATA #IMPLIED
    collection CDATA #REQUIRED
>

<!ELEMENT choose (when*,otherwise?)>

<!ELEMENT when (band|script|iterate|choose|call)*>
<!ATTLIST when
    test CDATA #REQUIRED
>

<!ELEMENT otherwise (band|script|iterate|choose|call)*>

<!ELEMENT call (argument)*>
<!ATTLIST call
    name CDATA #REQUIRED
>

<!ELEMENT argument (#PCDATA)>
<!ATTLIST argument
    name CDATA #REQUIRED
    value CDATA #IMPLIED
>

<!ELEMENT row EMPTY>
<!ATTLIST row
    height CDATA #IMPLIED
    top-margin CDATA #IMPLIED
    bottom-margin CDATA #IMPLIED
>

<!ELEMENT column EMPTY>
<!ATTLIST column
    width CDATA #IMPLIED
    left-margin CDATA #IMPLIED
    right-margin CDATA #IMPLIED
>

<!ELEMENT cell (block)*>
<!ATTLIST cell
    row-span CDATA #IMPLIED
    column-span CDATA #IMPLIED

    top-margin CDATA #IMPLIED
    bottom-margin CDATA #IMPLIED
    left-margin CDATA #IMPLIED
    right-margin CDATA #IMPLIED
    top-padding CDATA #IMPLIED
    bottom-padding CDATA #IMPLIED
    left-padding CDATA #IMPLIED
    right-padding CDATA #IMPLIED
    background CDATA #IMPLIED
    vertical-align (top|bottom|center) #IMPLIED
    align (left|right|center|justify) #IMPLIED
    border CDATA #IMPLIED
    border-left CDATA #IMPLIED
    border-right CDATA #IMPLIED
    border-top CDATA #IMPLIED
    border-bottom CDATA #IMPLIED
>

<!ELEMENT block (#PCDATA|wrapper|expression|image)*>
<!ATTLIST block
    condition CDATA #IMPLIED
    top-margin CDATA #IMPLIED
    bottom-margin CDATA #IMPLIED
    left-margin CDATA #IMPLIED
    right-margin CDATA #IMPLIED
    top-padding CDATA #IMPLIED
    bottom-padding CDATA #IMPLIED
    left-padding CDATA #IMPLIED
    right-padding CDATA #IMPLIED
    background CDATA #IMPLIED
    vertical-align (top|bottom|center) #IMPLIED
    align (left|right|center|justify) #IMPLIED
    border CDATA #IMPLIED
    border-left CDATA #IMPLIED
    border-right CDATA #IMPLIED
    border-top CDATA #IMPLIED
    border-bottom CDATA #IMPLIED

    font-family CDATA #IMPLIED
    font-style CDATA #IMPLIED
    font-size CDATA #IMPLIED
    foreground CDATA #IMPLIED
    background CDATA #IMPLIED
>

<!ELEMENT wrapper (#PCDATA|wrapper|expression|image)*>
<!ATTLIST wrapper
    font-family CDATA #IMPLIED
    font-style CDATA #IMPLIED
    font-size CDATA #IMPLIED
    foreground CDATA #IMPLIED
    background CDATA #IMPLIED
>

<!ELEMENT expression (#PCDATA)>
<!ATTLIST expression
    value CDATA #IMPLIED
    pass2 (true|false) #IMPLIED
>

<!ELEMENT image (#PCDATA)>
<!ATTLIST image
    value CDATA #IMPLIED
    alignment (top|bottom|hanging|center|roman) #IMPLIED
    width CDATA #IMPLIED
    height CDATA #IMPLIED
    origin-x CDATA #IMPLIED
    origin-y CDATA #IMPLIED
>

=== robbyn/pureport/test/test4.xml
<!DOCTYPE report PUBLIC "-//librebiz//DTD pureport 1.0//EN" "report.dtd">
<report default-units="cm">
    <page-layout left-margin="2.5cm" right-margin="1.5cm" top-margin="1.5cm" bottom-margin="1.5cm" />
    <macro name="processItem" arguments="position,item">
        <band>
            <row />
            <column width="9cm"/>
            <column />
            <column />
            <column />
            <column />
            <cell>
                <block align="left">
                    <wrapper font-family="Verdana" font-size="16pt" font-style="normal">
                        <expression value="position+1"/> 
                        <expression value="item.label"/>
                    </wrapper>
                </block>
            </cell>
            <cell>
                <block align="right">
                    <wrapper font-family="Verdana" font-size="16pt" font-style="bold">
                        <expression value='numberFormat.format(item.quantity)'/>
                    </wrapper>
                </block>
            </cell>
            <cell>
                <block align="right">
                    <wrapper font-family="Verdana" font-size="16pt" font-style="bold">
                        <expression value='numberFormat.format(item.price)'/>
                    </wrapper>
                </block>
            </cell>
            <cell>
                <block align="right">
                    <wrapper font-family="Verdana" font-size="16pt" font-style="bold">
                        <expression value='numberFormat.format(item.vat)'/>
                    </wrapper>
                </block>
            </cell>
            <cell>
                <block align="right">
                    <wrapper font-family="Verdana" font-size="16pt" font-style="bold">
                        <expression value='numberFormat.format(item.quantity*item.price*(1+item.vat))' />
                    </wrapper>
                </block>
            </cell>
        </band>
    </macro>
    <before>
        Quantity = Packages.org.librebiz.pureport.quantity.Quantity;
        ImageIO = Packages.javax.imageio.ImageIO;
        File = Packages.java.io.File;
        URL = Packages.java.net.URL;

        numberFormat = new java.text.DecimalFormat("0.00");
        intFormat = new java.text.DecimalFormat("0");
    </before>
    <page-header>
        <row />
        <column />
        <cell background="yellow">
            <block align="justify">
                <wrapper font-family="Verdana" font-size="16pt" font-style="bold">
                    <image value='new URL("file:test/test4.jpg")'/>Pour permettre une migration progressive, le serveur Linux peut être configuré en passerelle entre les réseaux 192.9.200.0 et 192.168.3.0 il prendra l'adresse 192.9.200.254 qui est l'actuelle adresse de la passerelle par défaut, et le routeur pourra prendra son adresse définitive: 192.168.3.1. Les autres postes pourront être migrés progressivement.
                </wrapper>
            </block>
            <block border="2pt solid black" align="center" left-margin="0.5cm" right-margin="0.5cm" top-margin="0.5cm" bottom-margin="0.5cm" background="cyan">
                <wrapper font-family="Verdana" font-size="24pt" font-style="bold">
                    <expression value="new Date()"/>
                </wrapper>
            </block>
            <block align="justify">
                <wrapper font-family="Verdana" font-size="16pt" font-style="bold">
Pour permettre une migration progressive, le serveur Linux peut être configuré en passerelle entre les réseaux 192.9.200.0 et 192.168.3.0 il prendra l'adresse 192.9.200.254 qui est l'actuelle adresse de la passerelle par défaut, et le routeur pourra prendra son adresse définitive: 192.168.3.1. Les autres postes pourront être migrés progressivement.
                </wrapper>
            </block>
        </cell>
    </page-header>
    <page-footer>
        <row />
        <column />
        <cell background="yellow">
            <block align="center">
                <wrapper font-family="Verdana" font-size="24pt" font-style="bold">
                    - <expression value="pageNumber"/>/<expression value="pageCount" pass2="true"/> -
                </wrapper>
            </block>
        </cell>
    </page-footer>
    <iterate collection="items" id="elm" index-id="ix">
        <call name="processItem">
            <argument name="item" value="elm"/>
            <argument name="position" value="ix"/>
        </call>
        <iterate collection="elm.subItems" id="sub" index-id="jx">
            <call name="processItem">
                <argument name="item" value="sub"/>
                <argument name="position" value="jx"/>
            </call>
        </iterate>
    </iterate>
    <iterate collection="items" id="elm" index-id="ix">
        <choose>
            <when test="ix%2 == 0">
                <band>
                    <row />
                    <column />
                    <cell>
                        <block align="right">
                            <wrapper font-family="Verdana" font-size="16pt" font-style="bold">
                                <expression value="elm.label"/>: 
                                <expression value='numberFormat.format(elm.quantity*elm.price*(1+elm.vat))' />
                            </wrapper>
                        </block>
                    </cell>
                </band>
                
            </when>
            <otherwise>
                <band>
                    <row />
                    <column />
                    <cell background="pink">
                        <block align="right">
                            <wrapper font-family="Verdana" font-size="16pt" font-style="bold">
                                <expression value="elm.label"/>: 
                                <expression value='numberFormat.format(elm.quantity*elm.price*(1+elm.vat))' />
                            </wrapper>
                        </block>
                    </cell>
                </band>
            </otherwise>
        </choose>
    </iterate>
</report>
